keys:
  - &users:
    - &aeacus age16352qhwjh9p6na2aadc5p4a75vl04gmdcwpecpl7u3d7f3ktuqdqclk5ak
  - &hosts:
    - &melinoe age1csl4zmvjllk9h3lvlttzyxgp6gx8g0lknqda4qrwh959la55ze4q05jpwf
    - &andromeda age122cf9krynvapfjf50trpasvk9mpff9hl8qqmyy86w45kpzdqkpcsuk74mx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *aeacus
      - *melinoe
      - *andromeda
